name: release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.ref_name }}

  release:
    needs: [build]

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dartsdk-android-x64-${{ github.ref_name }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dartsdk-android-ia32-${{ github.ref_name }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dartsdk-android-arm64-${{ github.ref_name }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dartsdk-android-arm-${{ github.ref_name }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dartsdk-android-riscv64-${{ github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ endsWith(github.ref_name, '.beta') || endsWith(github.ref_name, '.dev') }}
          files: |
            dartsdk-android-x64-release.tar.gz
            dartsdk-android-ia32-release.tar.gz
            dartsdk-android-arm64-release.tar.gz
            dartsdk-android-arm-release.tar.gz
            dartsdk-android-riscv64-release.tar.gz

  container:
    needs: [release]

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dartsdk-android-x64-${{ github.ref_name }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dartsdk-android-ia32-${{ github.ref_name }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dartsdk-android-arm64-${{ github.ref_name }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dartsdk-android-arm-${{ github.ref_name }}

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dartsdk-android-riscv64-${{ github.ref_name }}

      - name: Docker Metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=edge
            type=ref,event=branch
            type=ref,event=pr
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/0.') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ !endsWith(github.ref_name, '.beta') && !endsWith(github.ref_name, '.dev') }}
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
